version: '3.8'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Servicio de la aplicación Node.js
  app:
    build: .
    container_name: node-app
    ports:
      - "4000:4000"  # Mapeo del puerto 4000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${URI}
    networks:
      - app-network
    volumes:
      - .:/app
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

